package.json
When running in a certain server runtimes v0.3.0 makes the assertion
that the `navigator` option is available on the global scope resulting
in the error `Cannot read property 'navigator' of undefined`.
This appears to be fixed in v0.4.
The offending line can be found here: https://github.com/emn178/js-md5/blob/v0.3.0/src/md5.js#L20
=> Update js-md5 to v0.4

src/imgix-core-js.js, test/test-client.js
This PR makes a few improvements to the `ImgixClient._sanitizePath()` method:
- If a full URL was passed in to the method with a leading slash, it was being treated like a relative path and wasn't being encoded properly. This has been fixed so any leading slash gets stripped before evaluating the given path for encoding purposes, then re-added before return.
- The method now gracefully handles both paths that are passed in both pre-encoded and unencoded by passing the given path through `decodeURIComponent()` up front. As far as my brain is able to imagine, this should be a perfectly safe procedure. The result is that paths passed in un-encoded get decoded (resulting in the exact same string) and then encoded, and paths that are passed in encoded get decoded and then re-encoded. 
- …
=> Improve `ImgixClient._sanitizePath()`

src/imgix-core-js.js, test/test-client.js
This PR is intended to fix the two issues brought up in #24, both of which involve encoding errors brought about by ham-fistedly decoding all paths fed in to the `_sanitizePath()` private method before attempting to re-encode things properly based on whether we determined the path was a fully qualified URL or just a path fragment.
Instead of this clumsy approach, we're now evaluating the given path up front to determine which of the following categories it falls into. Each category is then handled slightly differently:
- *Fully-qualified, unencoded URLs*. If the given path matches `/^https?:\/\//`, we assume its a fully-qualified, unencoded URL. All we need to do here is encode it as though it was a URI component (since it will be just a component, in the final imgix URL).
- …
=> Rework de/encoding in `_sanitizePath` method to be more careful

src/imgix-core-js.js, test/test-client.js
I had previously updated the `ImgixClient._sanitizePath()` method in an attempt to be clever and properly handle pre-encoded paths. This introduced unnecessary complexity into the method (detemining whether or not a given string is unencoded, sorta pre-encoded, or fully pre-encoded is trickier than it seems at first glance) and introduced stupid bugs into its base use-case.
Having failed my attempt at cleverness, I am suitably chagrined. This PR removes all code dealing with pre-encoded paths from `ImgixClient._sanitizePath()` so it only handle non-encoded inputs. Our README has instructed users to only pass in non-encoded data from the start:
> Whenever you provide data to imgix-core-js, make sure it is not already URL-encoded, as the library handles proper encoding internally.
This also …
=> Remove "clever" decoding from `_sanitizePath`

src/imgix-core-js.js
Fixed an issue with Base64 encoding when ImgixClient is initialized from the first case, i.e.
if (typeof define === 'function' && define.amd) {
define('Imgix', ['exports', 'md5', 'js-base64'], factory);
=> Fixed Base64 issue when define is defined

bower.json, src/constants.js, src/imgix-core-js.js, test/test-client.js
Adds a validation that will throw an error if a user attempts to initialize a new `ImgixClient` object with an invalid domain.
The validation criteria is based off of the same regex used on [dashboard.imgix.com](https://dashboard.imgix.com)
=> Add domain validation during ImgixClient initialization

README.md, src/imgix-core-js.js, test/test-client.js
This PR adds further detail to the sharding deprecation warning, alerting users that `settings.domains` will be deprecated in favor of `settings.domain`. This change should precede the domain sharding removal release.
=> docs: deprecate settings.domains

src/imgix-core-js.js, test/test-client.js
This PR is a follow up to #43, creating a new field in the `ImgixClient` object that will replace `settings.domains` once domain sharding is removed.
=> feat: add settings.domain argument

src/imgix-core-js.js
This PR removes the `host` argument as all domain initialization should be done with the `domain` argument.
=> fix: remove deprecated settings.host

src/imgix-core-js.js, test/test-client.js
This PR addresses a bug in which `ImgixClient` did not respect the `host` argument during initialization
=> fix: allow `ImgixClient` to be initialized by using the deprecated `host` argument

.travis.yml, package-lock.json, package.json
This PR removes node v4/adds v12 in the travis config
[More info](https://nodejs.org/en/about/releases/) on node LTS
=> ci(travis): update node versions

README.md, src/imgix-core-js.js, test/test-client.js
This PR adds a new function to the imgix-core-js interface that will either generate a width descriptor or DPR `srcset` based on the specified parameters.
Special attention should be given to cover all aspect ratio-related cases, especially with the newly available `ar` parameter.
=> feat: add srcset generation

README.md, src/imgix-core-js.js, test/test-client.js
This PR adds a few things that were missed in #53, namely:
- including the `dpr` parameter when generating a DPR srcset
- mentioning the use of `fit=crop` in documentation
- more test cases for default (no parameter) calls to `buildSrcSet()`, expected srcset pair values, and DPR mode
=> fix: include dpr parameter when generating fixed-width srcset

src/imgix-core-js.js, test/test-client.js
This PR updates the path-encoding logic in `_.sanitizePath()` to ensure that three characters are properly encoded: `#`, `?`, and `:`. These characters are all URL-legal, so they're untouched by `window.encodeURI()`, but since they're used to separate parts of a valid URL they must be encoded if they're to appear in the path.
=> fix: ensure URL-legal, path-illegal characters are encoded

package-lock.json, package.json
This PR changes the _typescript_ and _@types/node_ runtime dependencies to be `devDependencies` and `peerDependencies` instead. Typescript is not needed to run this library but is need for maintaining this project and will likely be a shared dependency on projects consuming it.
Resolves #76
=> build(deps): remove typescript as runtime dependency

README.md
As a follow up to #87, changes the npm version badge and fixes some inconsistencies in the README markdown.
=> docs: change npm badge; style changes

README.md, src/imgix-core-js.js, test/test-client.js
This PR adds support to specify a minimum and/or maximum width range when generating `srcset` pairs. In certain situations where the exact min and/or max renderable sizes are known, a user may want to tailor their `srcset` list to be more concise. This is now possible by passing a positive integer value to either the `minWidth` or `maxWidth` parameters, now a part of a new second optional arguent when invoking `buildSrcSet()`. Below is a demonstration of the new argument in action:
```js
var client = new ImgixClient({
domain:'testing.imgix.net',
includeLibraryParam: false
})
var srcset = client.buildSrcSet('image.jpg', {}, {minWidth:500, maxWidth: 2000})
```
This will generate a more specific `srcset` list as follows:
```html
https://testing.imgix.net/image.jpg?w=500 500w, …
```
=> feat: add support for defining a min and max srcset width

README.md, src/imgix-core-js.js, test/test-client.js
This PR adds logic which will allow users to modify the width tolerance used when building `srcset` width pairs. More specifically, the width tolerance dictates the maximum difference between entries in a `srcset` attribute that should be generated. By default, this rate is set to 8 (`0.08`) percent. Users can use this setting to fine tune how many `srcset` pairs they generate when calling `buildSrcSet()`.
A user can now specify their own tolerance rate by passing a positive scalar value to the `widthTolerance` within the method's optional third argument. See the following example:
```js
var client = new ImgixClient({
domain:'testing.imgix.net',
includeLibraryParam: false
})
var srcset = client.buildSrcSet('image.jpg', {}, {widthTolerance: .20})
console.log(srcset);
```
In this case, the …
=> feat: add support for defining a custom srcset width tolerance

README.md, src/imgix-core-js.js, test/test-client.js
This PR adds logic that allows users to pass in a custom widths list when generating `srcset` pairs.
In certain cases when users know exactly what widths they want to have their images rendered at, they will be able to pass in an array of positive integers as `widths` to the optional third object:
```js
var client = new ImgixClient({
domain:'testing.imgix.net',
includeLibraryParam: false
})
var srcset = client.buildSrcSet('image.jpg', {}, {widths: [100, 500, 1000, 1800]})
console.log(srcset);
```
Will generate the following `srcset` of width pairs:
```html
https://testing.imgix.net/image.jpg?w=100 100w,
https://testing.imgix.net/image.jpg?w=500 500w,
https://testing.imgix.net/image.jpg?w=1000 1000w,
https://testing.imgix.net/image.jpg?w=1800 1800w
```
It is important to note that in …
=> feat: add support for defining a custom srcset width array

README.md, src/imgix-core-js.js, test/test-client.js
This library will automatically append a variable `q` parameter mapped to each `dpr` parameter when generating a [fixed-image](https://github.com/imgix/imgix-core-js#fixed-image-rendering) srcset. This technique is commonly used to compensate for the increased filesize of high-DPR images. Since high-DPR images are displayed at a higher pixel density on devices, image quality can be lowered to reduce overall filesize without sacrificing perceived visual quality. For more information and examples of this technique in action, see [this blog post](https://blog.imgix.com/2016/03/30/dpr-quality).
This behavior will respect any overriding `q` value passed in as a parameter. Additionally, it can be disabled altogether by passing `{ disableVariableQuality: true }` to the third argument of …
=> feat: append variable qualities to dpr srcsets

src/imgix-core-js.js, test/test-client.js
This PR patches a hole in the validation that allowed a user to pass a value of `0` to either the `widthTolerance`, `minWidth`, and/or `maxWidth` fields in `createSrcSet()`. Beforehand, users would be able to pass a zero value to these fields - although it would usually end up being ignored. Now the validations are adjusted to throw an error. In addition to this patch, this PR also refactors/cleans-up a lot of the validation logic used in generating `srcset` pairs, pulling it out into its own separate private function. This should yield significantly more readable code.
=> fix: throw error when certain srcset modifiers are passed zero

src/imgix-core-js.js, test/test-client.js
This PR adds memoization to the `_generateTargetWidths` helper function, which is responsible for calculating the widths returned in a [fluid width](https://github.com/imgix/imgix-core-js#srcset-generation) `srcset`.
With memoization, the `ImgixClient` class will build an internal cache of widths as they are generated for the first time, which can then be accessed later on rather than be repeatedly recalculated. Part of this change requires exposing `_generateTargetWidths` on the class prototype, rather than maintaining it privately.
=> perf(srcset): memoize generated srcset width-pairs

src/imgix-core-js.d.ts, tsconfig.json
This PR adds TS definitions for the `srcset` modifier argument used in the `buildSrcSet()` method, which grants users the capability to fine-tune how their `srcset` value is generated. As part of this, we are able to provide users with an interface describing the available arguments that can be passed into this option, mapped to their expected variable types. Below is an example of intellisense completion listing these available arguments from a user's point of view.
Relates to #108, #109, #110, #111
=> feat: add srcset option parameter to buildSrcSet() method signature

src/imgix-core-js.js
This PR adds missing declarations left out from #114. This causes a ReferenceError when `ImgixClient` attempts to validate any `srcset` options, specifically in strict mode.
=> fix: add missing variable declarations

test/test-sdk-api.js
I made this PR because we are using this pseudo-public API in our Angular and Vue libraries (and probably others) to set `ixlib` to the correct value for that library. I thought it would be good idea to explicitly state this as a "imgix-public" API that we can depend on in SDK libraries, so we don't end up changing this library and breaking this API, and only realising down the track when we pull this library into other SDKs.
=> test: explicitly test overriding libraryParam for imgix SDKs

package-lock.json, package.json
This PR removes `phantomjs` as a devDependency. Not only is it no longer used anywhere in our test suite, but the package has been deprecated for some time. As a result of not being maintained, `phantomjs` has steadily had more security issues opened up against it, which have bubbled up to this project. See below the readout of `npm audit`:
```
found 14 vulnerabilities (3 low, 8 moderate, 3 high) in 362 scanned packages
14 vulnerabilities require manual review. See the full report for details.
```
Removing `phantomjs` will resolve 13 out of 14 of these issues. The remaining vulnerability will be resolved once #99 is merged.
CC: @ericdeansanchez
=> chore(deps): remove phantomjs devDependency

.github/CODEOWNERS
This PR adds [CODEOWNERS](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) to designate those responsible for maintaining this project to outside users/contributors. Currently, the default/only assignment points to @imgix/imgix-sdk-team.
=> chore: add project CODEOWNERS

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md
GitHub issue templates can only be auto-assigned to individual users, but unfortunately not teams. As a middle ground, we decided to include a line in the template body specifically mentioning the @imgix/ imgix-sdk-team team so users know who to expect a response from.
----------
=> chore: call-out @imgix/imgix-sdk-team in template

src/imgix-core-js.js, test/test-buildSrcSet.js, test/test-buildURL.js
The purpose of this PR is to ensure the `buildSrcSet` operation is
idempotent. Prior to this PR, code modified the input-parameters,
`params`, causing identical calls to `buildSrcSet` to produce different
results.
Now, the input `params` are copied into a new `queryParams` object and
this object is passed to callers requiring `params`. A test has been
written to show that the behavior has changed from the behavior detailed
in issue #158––the input `params` object remains unchanged after calling
`buildSrcSet` _and_ that calling `buildSrcSet` multiple times produces
the same result (given the same inputs).
I also ripgrep'd through the repo with `rg 'params.[:alpha:]'` and with
`rg 'params\['` to ensure `params` is never mutated (i.e. it never
appears on the left hand side of any …
=> fix(buildURL): ensure operation is idempotent

src/imgix-core-js.js
The purpose of this PR is to make `._buildSrcSetPairs` and
`._buildDPRSrcSet` more direct. Before, this PR both functions
were concatenating strings within a loop. In both functions, the
last URL string to be generated includes `",\n"` which is sliced off
when the functions return.
Now, both functions generate/build URLs that are pushed onto the
`srcset` array. The URLs in the `srcset` array are then joined together
with `",\n"`.
This change was made in an attempt to improve the semantics. E.g.
"build URLs and join them with ',\n'" versus "build URLs, concatenate
them, and remove the extra ',\n' from the result".
=> refactor: push-and-join instead of concat-and-slice

package-lock.json, package.json, tsconfig.json
I removed the peerDep on `@types/node` since it's not actually required, and updated the typescript peer dep to work with the oldest version of the type definitions that I could verify worked.
While creating this PR, I realised that we don't actually need a peer dependency on typescript since it a) forces non-TS consumers to install typescript as a dependency (otherwise they will have a persistent warning), and b) since our types work with TS versions all the way back to 1.5, we don't need to restrict the TS version that's installed, which makes the peer dependency redundant. Therefore I removed it.
=> chore: correct typescript-related dependencies

package-lock.json, package.json
This reverts commit 87f87153e7de896b51064f53073c543502511c3a merged from #153.
The original update introduced a breaking change that cut off support to older browsers and ES environments. For now, we will err on the side of not cutting off support and attempt to mitigate this issue in a different way later on.
=> chore: revert "fix(deps): update dependency js-base64 to v3"

.github/pull_request_template.md
At the bottom of the document it says "description should be ... written in the imperative-mood", so the example message should be "fix typo" rather than "fixed typo".
=> chore(pr template): fix contradiction regarding commit messages

src/imgix-core-js.js, test/test-buildSrcSet.js
Two commits. One adds a failing test case for a bug where in certain conditions the largest value in the srcset list is repeated. The other commit fixes the bug. Full details are in the commit messages.
See the new test for an example failing case.
`buildSrcSet('image.jpg', {}, {widthTolerance: 0.0999, minWidth: 1000, maxWidth: 1200})` was outputting [1000, 1200, 1200].
=> Fix repeated value

test/test-buildURL.mjs
The purpose of this PR is to ensure we use `const` where possible as
well as use the correct assertion order (i.e. actual, then expected).
Prior, there were some leftover `var`s etc. Now those have been removed
from multiple files.
Now we use `strictEqual` and `notStrictEqual`; we also use the assert
order expected by the assert functions.
=> test: const where possible, fix assert order

src/validators.mjs, test/test-buildSrcSet.mjs, test/test-validators.mjs
The purpose of this PR is to enforce a lower bound on `widthTolerance`.
Prior, `widthTolerance` was expected to be greater than zero. However,
accepting a number like `0.000000001` here can do more harm than good.
We don't expect that such a number represents an actual use-case,
rather, we're enforcing this lower bound to keep defaults sensible and
help users guard against undesirable/accidental input.
Now, we enforce a lower bound of `0.01` on `widthTolerance`. This is also
pretty lenient, e.g. with the min/max width defaults set and setting the width
tolerance down to `0.01` (to one percent) we can make a srcset with 224
image URLs in it where the widths progress like `100, 102, 104, 106,
108, 110...`.
=> feat: enforce 0.01 lower bound for widthTolerance

test/test-buildSrcSet.mjs
The purpose of this PR is to wrap duplicated code into functions.
This PR also fixes a bug in the testing of width tolerance increases.
Prior, we were testing that a 40% increase (`1.40`) was less than the
desired bound of `2.40`. Now, we add a small amount to the tolerance
upper bound (`0.004`) so that when we check increases that are slightly
more than 40% (e.g. 40.1%) we account for the rounding that occurs in
generating target widths.
=> test: deduplicate code using functions

README.md, src/main.mjs, test/test-buildSrcSet.mjs
The purpose of this PR is to ensure we create a DPR-based srcset when
a fixed height, `h`, is specified. Prior, we required that a `h` and
an aspect ratio (`ar`) be passed. Now, we require that only  a `w` or
`h` be specified to trigger a DPR-based srcset to be created.
Closes #177
=> feat: create a DPR srcset when a fixed height is specified

src/main.mjs
Prior, this function performed an array access, property access, and
a comparison in the loop condition. Now, this has been reduced to a
single comparison. Prior, this function made an additional function
call/comparison in the body (i.e. `Math.min`) on every iteration. Now,
that has been removed as well.
Prior, this function attempted to return a list resolutions before
checking the cache (i.e. `[minW]`). Now, we check the cache first.
Now, when the loop terminates we know that the last width to be pushed
is less than the currentWidth that caused the loop condition to fail
and its value is greater than or equal to `maxW`. We want to stop at
`maxW` exactly so we push it if it's less than the last resolution.
=> refactor: improve target widths generation

src/index.mjs, test/test-buildURL.mjs
While testing encoding behavior across the SDKs I found a failure to
encode this path: `"&$+,:;=?@#.jpg"`. Prior to this PR our encoding step
didn't replace plus signs (+). Now we replace plus signs with `%2B`.
To see that the original encoding step fails, replace the domain of this
URL `'https://test.imgix.net/&$+,%3A;=%3F@%23.jpg'` to see that it 404s.
Likewise, you can replace the domain of the this correctly encoded URL:
`'https://test.imgix.net/&$%2B,%3A;=%3F@%23.jpg'` to see that it 200s
(and the image is displayed).
For reference see [RF3986 - Appendix B](https://tools.ietf.org/html/rfc3986#appendix-B).
=> fix: percent encode plus signs in path components

README.md
This PR updates links and references from the previous naming convention
to the current one (`@imgix/js-core`).
=> docs: rename links and references

src/index.mjs, test/test-buildSrcSet.mjs
The purpose of this PR is to extend `targetWidths` functionality to
users via a static class function. A static function has been used to
preserve the import syntax for UMD, CommonJS, and ES6 modules.
Previously, this function was named `_generateTargetWidths` which
required users to instantiate an `ImgixClient` object to use it. Now,
this function has been renamed and re-implemented as a static function.
Previously, the parameter order required `widthTolerance`, `minWidth`,
and then `maxWidth`. The order has been changed in accordance with
how common a particular argument is expected to be passed:
```js
targetWidths(minWidth, maxWidth, widthTolerance, cache)
```
=> feat: static targetWidths functionality

src/imgix-js-core.d.ts
The purpose of this PR is to include the `targetWidths` function
in the `.d.ts` file.
=> chore(types): include targetWidths

package.json
The purpose of this PR is to change the prepublish-script to be named
as the prepare-script because [prepublish has been deprecated](https://docs.npmjs.com/cli/v7/using-npm/scripts#prepare-and-prepublish).
Since `npm@4.0.0`, `prepare`:
- runs any time before the package is packed, i.e. during npm publish and npm pack
- runs BEFORE the package is packed
- runs BEFORE the package is published
- runs on local npm install without any arguments
=> build: use prepare over deprecated prepublish

src/validators.js
The error message isn't quite correct, so I improved it a little.
=> fix: improve error messages for target width validator

test/test-pathEncoding.js
This PR adds more path encoding tests.
This PR chose to make a new file for these tests. An argument could be make for leaving these inside the `buildURL` tests. For the sake of making these as easy to read and find as possible, they were left in a separate file.
=> test(encoding): add path encoding tests to img url that resolves

src/constants.js
The inclusion of the prefix (e.g. `ixlib=js-v3.1.3`) causes issues in our internal reporting that result in versions of this libray with the prefix to not be correctly captured. This commit removes the prefix to match the format previous to the current major version.
=> fix: remove "v" prefix from `VERSION` constant

src/index.js, test/test-buildURL.js
This PR ensures that undefined parameters are not added to the
params object generated by _buildParams. This way, undefined params do
not then end up in the generated URL.
=> fix: ensure undefined parameters not added to URL 

assert_version.cjs
#289 removed the "v" prefix from the src `VERSION` constant. The `assert_version` script confirms that the aforementioned constant matches that in the project package.json
Instead of relying on an exact string match, we can check that the src version (no prefix) is a subset of the package version (with prefix). In this way, `v3.0.0 == 3.0.0` will be true.
I debated removing the prefix from the package version as well but held off in case it somehow negatively affects in the future when we try to add semantic release in this project.
=> build: assert that versions match without relying on the "v" prefix

package-lock.json, package.json, rollup.config.js, src/helpers.js, src/index.js, test/test-_buildSrcSet.js, test/test-_buildURL.js, test/test-extractURL.js, types/index.d.ts
This PR adds full URL support to the client via static methods
-  `_buildURL` 
- `_buildSrcSet`
Unit tests for these methods are included in the PR.
The PR also introduces a helper function, `extractUrl` that uses the `ufo` module to parse and isolate different URL components of a full URL. Unit tests for the helper function are also included in the PR.
The PR also introduces `ufo` [package](https://github.com/unjs/ufo) as a dependency.
```js
const client = ImgixClient
const params = { w: 100 }
const opts = { useHttps: true }
const src = "sdk-test.imgix.net/amsterdam.jpg?h=100"
const url = client._buildURL(src, params, opts)
const srcSet = client._buildSrcSet(src, params, opts)
console.log(url) // => "https://sdk-test.imgix.net/amsterdam.jpg?h=100&w=100"
console.log(srcSet) /** =>
* …
```
=> feat: full URL support for buildUrl and buildSrcSet

types/index.d.ts
Adds the following missing types to `types/index.d.ts`
```js
// * @param {Object} srcsetModifiers - srcset modifiers, optional
// * @param {Object} clientOptions - imgix client options, optional
```
So that `_buildSrcSet` types are defined as
```ts
static _buildSrcSet(
path: string,
params?: {},
srcSetOptions?: {},
clientOptions?: {},
): string;
```
=> fix: add missing types to `_buildSrcSet` type declaration

.gitignore, .travis.yml, package-lock.json, package.json
This commit enables semantic release on main, next, beta, and alpha
branches. It includes most of `54185bfb20dae093bfadff9ed79c2e2848bb4d7f`, except the `@` nesting for `next` has been removed (ie fixed) and releases are enabled in all branches, no just `next`.
The `next` branch should not be deleted once this is merged in. There is a pre-release that's still based on its current state. Instead, once this branch is merged in, `next` should make a merge commit, bringing the two branches in sync. 
Once the pre-release feature has been release on main, _then_ the `next` branch can be safely deleted.
=> build: enable semantic release on all branches

README.md, src/index.js, test/test-pathEncoding.js, types/index.d.ts, types/index.test-d.ts
Before this PR, this library would encode all paths passed to either `buildURL` or `buildSrcSet`. This was a great default in a lot of scenarios, but this proved to be irritating when integrating with some data sources that provided already encoded URL paths. Thus, this PR allows this path encoding behavior to be disabled in the `options` parameter for both methods.
=> feat: allow path encoding to be disabled

package-lock.json, package.json, src/helpers.js, src/index.js, test/test-_buildSrcSet.js, test/test-_buildURL.js, test/test-extractURL.js, types/index.d.ts, types/index.test-d.ts
This PR creates static `_buildURL` and `_buildSrcSet` methods on the imgix client. These methods allow absolute URLs to be formatted for use with the imgix client.
- _buildURL
```
*`_buildURL` static method allows full URLs to be formatted for use with
* imgix.
*
* - If the source URL has included parameters, they are merged with
* the `params` passed in as an argument.
* - URL must match `{host}/{pathname}?{query}` otherwise an error is thrown.
```
- _buildSrcSet:    
```
* _buildSrcSet static method allows full URLs to be used when generating
* imgix formatted `srcset` string values.
*
* - If the source URL has included parameters, they are merged with
* the `params` passed in as an argument.
* - URL must match `{host}/{pathname}?{query}` otherwise an error is thrown.
```
=> feat: add _buildURL and _buildSrcSet static methods

package-lock.json, package.json, src/helpers.js, src/index.js, test/test-_buildSrcSet.js, test/test-_buildURL.js, test/test-extractURL.js, types/index.d.ts, types/index.test-d.ts
This PR creates a static `_buildURL` & `_buildSrcSet` methods on the imgix client. The methods allow absolute URLs to be formatted for use with imgix.
> note: If the source URL has included parameters, they are merged with
the `params` passed in as an argument.
- `url`: full source URL path string, required
- URL must match `{host}/{pathname}?{query}` otherwise an error is thrown.
- `params`: imgix params object, optional
- `options`: imgix client options, optional
=> feat: add static buildURL and buildSrcSet methods

README.md
Adds note pointing to imgix-management-js for users seeking management API support
closes #322
=> docs: add notice pointing to management-js library

README.md
Added a warning about using the `secureURLToken` option only on the server. In doing so, I realized there's a similar warning in the browser example right above it. 🤷
=> docs(readme): additional warning about the `secureURLToken` parameter

.circleci/config.yml
Adds an additional test step to our CircleCI process to test successful builds.
Problems with builds can only be detected by CircleCI during the deploy step; this step only runs on `main` and prerelease branches. As a result, commits that break builds (included automated dependency updates by Renovate) in many cases might not be detected until after merge.
We now test for a successful build step on every branch, using both stable and LTS node versions.
=> ci(build): test if builds are successful during ci test step

package.json
Adds additional script to ensure properly updated `dist` prior to release.
Library is not guaranteed to execute a `build` step to properly update `dist` directory prior to deployment; as a result, some libraries include the prior release in their `dist` folder.
We include both a `prepare` and a `prepublishOnly` step to ensure that the library executes a build prior to deploying a release.
=> ci(deploy): add prepublishOnly step

README.md
Fixes an inconsistency in the `Disable Path Encoding` documentation. The code example uses `domain: 'testing.imgix.net'` but the returned URL showed `https://sdk-test.imgix.net/...`.
=> chore: clean up `Disable Path Encoding` code example

package-lock.json, package.json
This PR updates the `ufo` dependency to the next major release, [`1.0.1`](https://github.com/unjs/ufo/compare/v0.8.0...v1.0.1)
Closes #348
=> fix(deps): update ufo to 1.x

README.md, src/index.js, test/test-buildURL.js, types/index.d.ts, types/index.test-d.ts
Before this PR, the `encoder` buildParams option would only be applied to the non-base64 parameters (i.e. parameters whose values did not end in `64`). After this PR, the same encoder will be applied to base64 parameters as well.
It also adds an optional parameter `key` to the encoder which allows users to specify encoding logic conditional to the parameter key. This is helpful if users wish to encode base64 and non-base64 parameters differently.
- [] ~~Update or add any necessary API documentation (if applicable)~~
- [] ~~Add some [steps](#steps-to-test) so we can test your bug fix or feature (if applicable).~~
- [] ~~Any breaking changes are specified on the commit on which they are introduced with `BREAKING CHANGE` in the body of the commit.~~
- [] ~~If this is a big feature with …
=> fix: apply custom encoder to base64 parameters

.circleci/config.yml
Node version 20.3 introduces a concurrency issue where the same file is getting accessed by multiple things as part of the rollup process. Unsure as to the root cause, but this commit pins current to 20.2 to resolve the build issues for now.
A future commit should either fix the 20.3 issues.
=> ci: pin node to lts and 20.2
